#!/bin/bash
#Author: Miguel Lorenzo, luzemail at gmail 
#date:
#license: GPLv3

#initialite var 
function initialiteVars {
	#the array
	#declare -a LETTERS
	LETTERS=()
}
 
#this function returns a randon word from the 
#word list located in the file /usr/share/dict/linux.words 
function getRandomWord {
	#we need to know how many words are in the file
	maxwords=$(wc -l /usr/share/dict/linux.words |awk '{print $1}')
	#we generate a random number between 1 and the max num of words
	#$RANDOM is an internal var that generates a random number
	line=$((RANDOM % maxwords))
	#now we get the word from the file
	toret=$( head -n $line /usr/share/dict/linux.words | tail -n 1  )	
	echo "$toret"
}

#print the number of letters used
function printDiscoveredLetters {
	discovered=""
	for ((x=0;x<$secretlenght;x++))
	do
		discovered+=" _ "
	done
	echo "Your String is $discovered"
}

#receives two parameters
#    Array array that contains a char list
#    Character to check
#    returns true if elements exist in array otherwise false
function existInArray {
	toret=false
	arrayElements=("${!1}")
	echo "${arrayElements[@]}"
	for character in "${arrayElements[*]}"
	do
	   if [ "$character" == "$2" ];
	   then  
		toret=true
	   fi
	done
	#$1 array
        #$2 char	
	echo $toret
}

#Ask the user to add a new letter
function askLetter {
	echo "write a letter to check"
	read -n 1 letter
	LETTERS[${#LETTERS[@]}+1]=letter
        echo "array size == ${#LETTERS[@]}"#LETTERS

}

function letterhasadded {
	toret=false
        #todo array length
    	for ((x=0;x<10;x++))
	do
		echo "fill me"
	done

}



#http://wiki.bash-hackers.org/syntax/arrays
initialiteVars
echo "array size == ${#LETTERS[@]}"#LETTERS

LETTERS[${#LETTERS[@]}]='a'
LETTERS[${#LETTERS[@]}]='b'
LETTERS[${#LETTERS[@]}]='c'
LETTERS[${#LETTERS[@]}]='d'
exist=$(existInArray LETTERS[@] 'c')
if (( $(existInArray LETTERS[@] 'c') ));
then
	echo "existInArray returns true"
fi
echo "array size == ${#LETTERS[@]}"#LETTERS
secretword=$(getRandomWord)
secretlenght=${#secretword}
trys=$secretlenght
for ((x=0;x<$secretlenght;x++))
do
 echo ${secretword:x:1}
done
echo "the secret word is $secretword and the lenght is ${#secretword}"
while [ $trys -gt 0 ]
do
	printDiscoveredLetters
	askLetter
	(( trys-- ))
done

