#!/bin/bash
#Author: Miguel Lorenzo, luzemail at gmail 
#date:
#license: GPLv3
 
#this function returns a randon word from the 
#word list located in the file /usr/share/dict/linux.words 
function getRandomWord {
	#we need to know how many words are in the file
	maxwords=$(wc -l /usr/share/dict/linux.words |awk '{print $1}')
	#we generate a random number between 1 and the max num of words
	#$RANDOM is an internal var that generates a random number
	line=$((RANDOM % maxwords))
	#now we get the word from the file
	toret=$( head -n $line /usr/share/dict/linux.words | tail -n 1  )	
	echo "$toret"
}

#print the number of letters used
function printDiscoveredLetters {
	discovered=""
	for ((x=0;x<$secretlenght;x++))
	do
		discovered+=" _ "
	done
	echo "Your String is $discovered"
}

#Ask the user to add a new letter
function askLetter {
	echo "write a letter to check"
	read letter
}

#askLetter
secretword=$(getRandomWord)
secretlenght=${#secretword}
trys=$secretlenght
echo "the secret word is $secretword and the lenght is ${#secretword}"
while [ $trys -gt 0 ]
do
	printDiscoveredLetters
	askLetter
	(( trys-- ))
done

